import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Muhammad Azhar | AI Engineer",
  description:
    "AI Engineer who builds and deploys AI models, APIs, and generative AI systems that deliver 10x workflow gains.",
  keywords: [
    "ai engineer",
    "machine learning",
    "generative ai",
    "llm",
    "rag",
    "ai api",
    "computer vision",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Muhammad Azhar",
    url: "https://github.com/azharthegeek",
  },
  openGraph: {
    title: "Muhammad Azhar | AI Engineer",
    description:
      "AI Engineer who builds and deploys AI models, APIs, and generative AI systems that deliver 10x workflow gains.",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Muhammad Azhar | AI Engineer",
    description:
      "AI Engineer who builds and deploys AI models, APIs, and generative AI systems that deliver 10x workflow gains.",
  },
} as const;
